module.exports = [{"id":1,"firstName":"Obie","lastName":"Brightey","age":1996,"username":"obrightey0","email":"obrightey0@networkadvertising.org","password":"MLzKfp5","role":"Estimator"},
{"id":2,"firstName":"Karolina","lastName":"Colcutt","age":2010,"username":"kcolcutt1","email":"kcolcutt1@sciencedirect.com","password":"EXhdLlYSnpu","role":"Construction Worker"},
{"id":3,"firstName":"Quintina","lastName":"Hadfield","age":2004,"username":"qhadfield2","email":"qhadfield2@reuters.com","password":"6D0ATL","role":"Construction Foreman"},
{"id":4,"firstName":"Biron","lastName":"Rizzi","age":1997,"username":"brizzi3","email":"brizzi3@infoseek.co.jp","password":"Kc3GPeSIDVp2","role":"Subcontractor"},
{"id":5,"firstName":"Dyann","lastName":"Fawley","age":2000,"username":"dfawley4","email":"dfawley4@zimbio.com","password":"0XYrRO8qUc2c","role":"Electrician"},
{"id":6,"firstName":"Beverlee","lastName":"Bonas","age":1987,"username":"bbonas5","email":"bbonas5@weebly.com","password":"5nptdEZ","role":"Construction Foreman"},
{"id":7,"firstName":"Austin","lastName":"Korneluk","age":1992,"username":"akorneluk6","email":"akorneluk6@edublogs.org","password":"MMOlYurPczIg","role":"Architect"},
{"id":8,"firstName":"Dinah","lastName":"Dermott","age":2005,"username":"ddermott7","email":"ddermott7@yale.edu","password":"eiFTm2HXGJ","role":"Project Manager"},
{"id":9,"firstName":"Melonie","lastName":"Devas","age":2003,"username":"mdevas8","email":"mdevas8@phpbb.com","password":"y70P8yBH","role":"Surveyor"},
{"id":10,"firstName":"Hobey","lastName":"Hickford","age":2008,"username":"hhickford9","email":"hhickford9@home.pl","password":"9aFW7sduA","role":"Supervisor"}]